package com.banking.system.transaction.domain.model;

import com.banking.system.common.domain.Money;
import lombok.Getter;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

@Getter
public class Transaction {
    private final UUID id;
    private final UUID accountId;
    private final TransactionType transactionType;
    private final Money amount;
    private final Money balanceAfter;
    private final Description description;
    private final ReferenceNumber referenceNumber;
    private final UUID relatedTransactionId; // only for transfers
    private final Instant executedAt;
    private final TransactionStatus status;

    public Transaction(UUID id,
                       UUID accountId,
                       TransactionType transactionType,
                       Money amount, Money balanceAfter,
                       Description description,
                       ReferenceNumber referenceNumber,
                       UUID relatedTransactionId,
                       TransactionStatus status,
                       Instant executedAt) {
        Objects.requireNonNull(accountId, "Account ID cannot be null");
        Objects.requireNonNull(transactionType, "Transaction type cannot be null");
        Objects.requireNonNull(amount, "Amount cannot be null");
        Objects.requireNonNull(referenceNumber, "Reference number cannot be null");
        Objects.requireNonNull(status, "Transaction status cannot be null");
        Objects.requireNonNull(executedAt, "Executed at timestamp cannot be null");

        this.id = id;
        this.accountId = accountId;
        this.transactionType = transactionType;
        this.amount = amount;
        this.balanceAfter = balanceAfter;
        this.description = description;
        this.referenceNumber = referenceNumber;
        this.relatedTransactionId = relatedTransactionId;
        this.status = status;
        this.executedAt = executedAt;
    }

    /**
     * Factory method for creating a new transaction aggregate from the application layer.
     * <p>
     * This method should be used when recording a brand new transaction that does not
     * yet exist in the persistence layer. It intentionally sets the {@code id} to
     * {@code null} so that the persistence mechanism can generate it, initializes the
     * transaction in {@link TransactionStatus#PENDING} status, and sets {@code executedAt}
     * to {@link Instant#now()}.
     * </p>
     *
     * @param accountId            identifier of the account this transaction belongs to (must not be {@code null})
     * @param transactionType      type of transaction (DEPOSIT, WITHDRAWAL, TRANSFER_OUT, TRANSFER_IN) (must not be {@code null})
     * @param amount               {@link Money} value object representing the transaction amount (must not be {@code null})
     * @param balanceAfter         {@link Money} value object representing the account balance after this transaction
     * @param description          {@link Description} value object containing transaction details (may be {@code null})
     * @param referenceNumber      {@link ReferenceNumber} value object for tracking and reconciliation (must not be {@code null})
     * @param relatedTransactionId optional identifier linking to a related transaction (for transfers)
     * @return a new {@link Transaction} instance representing a non-persisted transaction in PENDING status
     */
    public static Transaction createNew(
            UUID accountId,
            TransactionType transactionType,
            Money amount,
            Money balanceAfter,
            Description description,
            ReferenceNumber referenceNumber,
            UUID relatedTransactionId
    ) {
        return new Transaction(
                null,
                accountId,
                transactionType,
                amount,
                balanceAfter,
                description,
                referenceNumber,
                relatedTransactionId,
                TransactionStatus.PENDING,
                Instant.now()
        );
    }

    /**
     * Factory method for reconstituting an existing transaction aggregate from persistence.
     * <p>
     * This should be used by repository implementations when loading a transaction
     * from the database. All fields, including {@code id}, {@code status}, and
     * {@code executedAt}, are expected to come from a trusted source (e.g. JPA entity,
     * database row) and represent the actual state of the transaction.
     * </p>
     *
     * @param id                   unique identifier that has already been generated by the persistence layer
     * @param accountId            identifier of the account this transaction belongs to
     * @param transactionType      type of transaction reconstituted from persistence
     * @param amount               {@link Money} value object reconstituted from the persisted amount
     * @param balanceAfter         {@link Money} value object reconstituted from the persisted balance
     * @param description          {@link Description} value object reconstituted from the persisted description
     * @param referenceNumber      {@link ReferenceNumber} value object reconstituted from the persisted reference
     * @param relatedTransactionId optional identifier linking to a related transaction (for transfers)
     * @param status               current status of the transaction (PENDING, COMPLETED, FAILED, REVERSED)
     * @param executedAt           timestamp when the transaction was executed
     * @return a fully initialized {@link Transaction} instance representing an existing transaction
     */
    public static Transaction reconstitute(
            UUID id,
            UUID accountId,
            TransactionType transactionType,
            Money amount,
            Money balanceAfter,
            Description description,
            ReferenceNumber referenceNumber,
            UUID relatedTransactionId,
            TransactionStatus status,
            Instant executedAt
    ) {
        return new Transaction(
                id,
                accountId,
                transactionType,
                amount,
                balanceAfter,
                description,
                referenceNumber,
                relatedTransactionId,
                status,
                executedAt
        );
    }
}
