package com.banking.system.auth.domain.model;

import lombok.*;

import java.util.Objects;
import java.util.UUID;

@Getter
public class User {
    private final UUID id;
    private String email;
    private String passwordHash;
    private UserStatus status; // ACTIVE, BLOCKED, PENDING_VERIFICATION
    private Role role; // CUSTOMER, ADMIN, BRANCH_MANAGER

    public User(UUID id, String email, String passwordHash, UserStatus status, Role role) {
        Objects.requireNonNull(email, "email cannot be null");
        Objects.requireNonNull(passwordHash, "passwordHash cannot be null");
        Objects.requireNonNull(status, "status cannot be null");
        Objects.requireNonNull(role, "role cannot be null");

        this.id = id;
        this.email = email;
        this.passwordHash = passwordHash;
        this.status = status;
        this.role = role;
    }

    /**
     * Factory method for creating a new user aggregate from the application layer.
     * <p>
     * This method should be used when registering a brand new user that does not
     * yet exist in the persistence layer. It intentionally sets the {@code id}
     * to {@code null} so that the persistence mechanism can generate it, and
     * initializes the user in the {@link UserStatus#PENDING_VERIFICATION}
     * state with the default {@link Role#CUSTOMER} role.
     * </p>
     *
     * @param email        raw email address provided during registration (must not be {@code null})
     * @param passwordHash already hashed password value (must not be {@code null})
     * @return a new {@link User} instance representing a non-persisted user awaiting verification
     */
    public static User createNew(String email, String passwordHash) {
        return new User(
                null,
                email,
                passwordHash,
                UserStatus.PENDING_VERIFICATION,
                Role.CUSTOMER
        );
    }

    /**
     * Factory method for reconstituting an existing user aggregate from persistence.
     * <p>
     * This should be used by repository implementations when loading a user
     * from the database. All fields, including {@code id}, {@code status} and
     * {@code role}, are expected to come from a trusted source (e.g. JPA entity,
     * database row) and represent the current state of the user.
     * </p>
     *
     * @param id           unique identifier that has already been generated by the persistence layer
     * @param email        persisted email address
     * @param passwordHash persisted hashed password
     * @param status       current lifecycle status of the user
     * @param role         current role assigned to the user
     * @return a fully initialized {@link User} instance representing an existing user
     */
    public static User reconsitute(UUID id, String email, String passwordHash, UserStatus status, Role role) {
        return new User(
                id,
                email,
                passwordHash,
                status,
                role
        );
    }

    public void activate() {
        if (this.status != UserStatus.PENDING_VERIFICATION)
            throw new IllegalStateException("Only users with PENDING_VERIFICATION status can be activated");

        this.status = UserStatus.ACTIVE;
    }

    public void block() {
        if (this.status != UserStatus.ACTIVE)
            throw new IllegalStateException("Only ACTIVE users can be blocked");

        this.status = UserStatus.BLOCKED;
    }
}
